# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 04:24
from __future__ import unicode_literals

import apps.lunchbox.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lunchbox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lunchbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('description', models.TextField(blank=True, max_length=500)),
                ('city', models.CharField(max_length=150)),
                ('offertime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(related_name='lunchboxes', to='lunchbox.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunchboxes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LunchboxImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.lunchbox.models.lunchbox_directory_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lunchbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lunchbox.Lunchbox')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunchboxImages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('lunchbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='lunchbox.Lunchbox')),
            ],
        ),
    ]
