# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchbox', '0002_lunchbox_lunchboximage_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunchbox',
            name='lat',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='lunchbox',
            name='lon',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='lunchbox',
            name='offertime',
            field=models.DateTimeField(blank=True),
        ),
    ]
