# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchbox', '0003_auto_20180130_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunchbox',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='lunchbox',
            name='lon',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='lunchbox',
            name='offertime',
            field=models.DateTimeField(null=True),
        ),
    ]
