# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-09 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchbox', '0005_lunchbox_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='category_id',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='lunchboximage',
            name='image',
            field=models.ImageField(upload_to='media/test/'),
        ),
    ]
