# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-26 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchbox', '0010_auto_20180322_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunchbox',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
