# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-17 07:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lunchbox', '0011_lunchbox_display'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lunchbox',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='lunchbox',
            name='likedby',
            field=models.ManyToManyField(related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
